# send post request to http://localhost:5000/api/v1/login
POST http://localhost:5000/api/v1/login HTTP/1.1
content-type: application/json
accept: "application/json"

{
    "email": "ayomidedaniel00@gmail.com",
    "password": "password"
}